apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        name: node-exporter
      name: node-exporter
      annotations:
        prometheus.io/scrape: 'true'
        co.elastic.metrics/module: prometheus
        co.elastic.metrics/metricsets: collector
        co.elastic.metrics/hosts: '${data.host}:9100'
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
      hostNetwork: true
      hostPID: true
